@startuml
actor Студент
Студент -> Система: Запуск сервера
Система -> Система: Открытие порта 61499
Студент -> Система: Отправка команды CREATE
Система --> Студент: <Response OK>
Студент -> Система: Фаззинг (fuzzer.py)
Система -> Система: Краш → core dump
Студент -> Система: Анализ gdb
@enduml